version: '3.8'

services:
  lima-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./Diagnostic_Plantes.h5:/app/Diagnostic_Plantes.h5
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3